// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UcakTakip.Api.Data;

#nullable disable

namespace UcakTakip.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251014225915_Patch01_ValidationAndQueries")]
    partial class Patch01_ValidationAndQueries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UcakTakip.Api.Models.UcakKonum", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double?>("Altitude")
                        .HasColumnType("float");

                    b.Property<double?>("Heading")
                        .HasColumnType("float");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<DateTime>("TimestampUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("UcusPlaniId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UcusPlaniId", "TimestampUtc");

                    b.ToTable("UcakKonumlari");
                });

            modelBuilder.Entity("UcakTakip.Api.Models.UcusPlani", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTimeUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.ToTable("UcusPlanlari");
                });

            modelBuilder.Entity("UcakTakip.Api.Models.UcakKonum", b =>
                {
                    b.HasOne("UcakTakip.Api.Models.UcusPlani", "UcusPlani")
                        .WithMany("UcakKonumlari")
                        .HasForeignKey("UcusPlaniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UcusPlani");
                });

            modelBuilder.Entity("UcakTakip.Api.Models.UcusPlani", b =>
                {
                    b.Navigation("UcakKonumlari");
                });
#pragma warning restore 612, 618
        }
    }
}
